### PR TITLE
ED-1239 OCI OSS Support

### PR DESCRIPTION
**Pull request by subhashchandrab**
Updated deployment code to support OCI object storage

### Type of change

Please choose appropriate options.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### How Has This Been Tested?

Please describe the tests that you ran to verify your changes in the below checkboxes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [X] Executed jenkins build job Deploy/Lern/LernDataProducts

### CODE REVIEW

**Comment by maheshkumargangula** [comment]
@reshmi-nair - Please review the PR.
Cc: @gandham-santhosh

**Review by AmiableAnil — APPROVED** [review]

**Comment by AmiableAnil** [comment]
@subhashchandrab @ddevadat CircleCi is failing. Please follow the following fix here https://github.com/Sunbird-Lern/data-products/pull/51/files

**Comment by ddevadat** [comment]
closing in favour of 
https://github.com/Sunbird-Lern/data-products/pull/52

**Comment by ddevadat** [comment]
@subhashchandrab  please close this PR as we have combined it in 
https://github.com/Sunbird-Lern/data-products/pull/52

**Pull request closed without merging**
